import pyautogui
import pandas as pd
import time
time.sleep(3)
pyautogui.doubleClick(214, 50)
time.sleep(1)
pyautogui.click(300, 294)
time.sleep(10)
pyautogui.PAUSE = 0.3
tabela = pd.read_csv(r'C:\Users\Enzo\Desktop\csv abril 2.csv')
for linha in tabela.index:
	pyautogui.click(1031, 209)
	time.sleep(2)
	mat = tabela.loc[linha, "MATRICULA"]
	pyautogui.write(str(tabela.loc[linha, "MATRICULA"]))
	time.sleep(2)
	pyautogui.press('enter')
	time.sleep(2)
	pyautogui.click(515, 338)
	time.sleep(2)
	pyautogui.click(904, 619)
	time.sleep(2)
	pyautogui.click(904, 619)
	time.sleep(2)
	pyautogui.click(904, 619)
	time.sleep(2)
	pyautogui.click(904, 619)
	time.sleep(2)
	pyautogui.click(772, 478)
	time.sleep(2)
	pyautogui.press('0')
	time.sleep(0.25)
	pyautogui.press(',')
	time.sleep(0.25)
	pyautogui.press('6')
	time.sleep(0.25)
	pyautogui.press('5')
	time.sleep(0.25)
	pyautogui.press('enter')
	time.sleep(2)
	pyautogui.press('3')
	time.sleep(0.25)
	pyautogui.press(',')
	time.sleep(0.25)
	pyautogui.press('0')
	time.sleep(0.25)
	pyautogui.press('enter')
	time.sleep(2)
	pyautogui.click(1019, 245)
	time.sleep(2)
